### ISSUE TITLE
Investigate bug on CSV Load

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#170]

**Comment by LongQuanNguyen** [comment]
Fixing this error on Google Chrome whenever the user loads a CSV through URL:
![Screenshot from 2024-03-05 23-13-06](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/assets/94843824/93329a2d-9da7-4320-9a3c-2cfe593159e5)

At first glance, the error is likely to be a Chrome security feature. The CSV content is still read in successfully. I have tried this with Firefox and no error was shown.

**Comment by Subzeero** [comment]
As per me and @LongQuanNguyen's investigation in this issue, we have discovered that this issues stems from our implementation of parsing CSV files in batches of 1000 rows to prevent PapaParse from crashing with very large files. In Chrome, this error appears because of Chrome's internal security controls, but it is not an actual JavaScript error. It is more like a security warning.

We investigated the source code of PapaParse where the GET request for the remote CSV URL is made, and there exists proper handling for the invalid header 'Content-Range'. As such, this message is one that we should be able to safely ignore since it is not directly in our local codebase, but rather PapaParse's codebase where it is safely handled. 

This message appears in Chrome, but not others browsers since it is not an actual JavaScript error, but a security check that Chrome is conducting. Our CSV implementation works properly in the presence of this message.
