### ISSUE TITLE
Create ESLint CI/CD

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#64]
Write the build step for The ESLint

**Comment by Subzeero** [comment]
Marked this down as a blocked item for ID2 since we were still formulating a style guide. Going to commit to it for ID3.

Now that we have [one](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Style-Sheet-for-Typescript-and-React), and since it is based on Google's TS Style Guide, I was thinking https://github.com/google/gts might be a good fit to implement. It seems to use eslint under the hood, but will set up the appropriate rules for us.
